included:
  - Sources
  - Tests

excluded:
  - .build

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

disabled_rules:
  - trailing_comma
  - opening_brace

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
